# name: Terraform Delete Bucket Workflow

# on:
#   workflow_dispatch:
#     inputs:
#       bucket_name:
#         description: 'Name of the AWS S3 bucket to delete'
#         required: true

# env:
#   TF_VAR_bucket_name: ${{ github.event.inputs.bucket_name }}
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# jobs:
#   terraform:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: eu-west-2   # Adjust the region as per your requirement

#       - name: Download Terraform
#         run: |
#           wget https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip
#           unzip terraform_1.1.0_linux_amd64.zip
#           sudo mv terraform /usr/local/bin/
#           terraform --version

#       - name: Terraform Init
#         run: terraform init
#         working-directory: ././

#       - name: Terraform Plan
#         run: terraform plan -destroy
#         working-directory: ././

#       - name: Terraform Destroy
#         run: terraform destroy -auto-approve
#         working-directory: ././
      

name: Terraform Delete Bucket Workflow

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'Name of the AWS S3 bucket to delete'
        required: true

env:
  TF_VAR_bucket_name: ${{ github.event.inputs.bucket_name }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2   # Adjust the region as per your requirement

      - name: Download Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip
          unzip terraform_1.1.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version

      - name: Terraform Init
        run: terraform init
        working-directory: ././

      - name: Terraform Plan
        run: terraform plan -destroy -out=tfplan
        working-directory: ././

      - name: Delay Before Destroy
        run: sleep 30  # Adjust the delay time as needed

      - name: Terraform Apply
        if: steps.terraform.outputs.exit-code == 0
        run: terraform apply -auto-approve tfplan
        working-directory: ././
